<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Process Error/Bug</title>
    <link>https://community.keyauth.cc/t/process-error-bug/477</link>
    <description>![image|612x38](upload://xnrG2Fqw0csGXPQMnFt3BHAnAiy.png)</description>
    
    <lastBuildDate>Sun, 28 Aug 2022 10:50:56 +0000</lastBuildDate>
    <category>Python</category>
    <atom:link href="https://community.keyauth.cc/t/process-error-bug/477.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Process Error/Bug</title>
        <dc:creator><![CDATA[6nz]]></dc:creator>
        <description><![CDATA[
            
          <p><a href="https://community.keyauth.cc/t/process-error-bug/477/4">Read full topic</a></p>
        ]]></description>
        <link>https://community.keyauth.cc/t/process-error-bug/477/4</link>
        <pubDate>Sun, 28 Aug 2022 10:51:05 +0000</pubDate>
        <guid isPermaLink="false">community.keyauth.cc-post-477-4</guid>
        <source url="https://community.keyauth.cc/t/process-error-bug/477.rss">Process Error/Bug</source>
      </item>
      <item>
        <title>Process Error/Bug</title>
        <dc:creator><![CDATA[6nz]]></dc:creator>
        <description><![CDATA[
            <p>This is a program issue. Not keyauth example issue</p>
          <p><a href="https://community.keyauth.cc/t/process-error-bug/477/3">Read full topic</a></p>
        ]]></description>
        <link>https://community.keyauth.cc/t/process-error-bug/477/3</link>
        <pubDate>Sun, 28 Aug 2022 10:50:56 +0000</pubDate>
        <guid isPermaLink="false">community.keyauth.cc-post-477-3</guid>
        <source url="https://community.keyauth.cc/t/process-error-bug/477.rss">Process Error/Bug</source>
      </item>
      <item>
        <title>Process Error/Bug</title>
        <dc:creator><![CDATA[InstinctTheDevil]]></dc:creator>
        <description><![CDATA[
            <p>At what exact line does the error happen?</p>
          <p><a href="https://community.keyauth.cc/t/process-error-bug/477/2">Read full topic</a></p>
        ]]></description>
        <link>https://community.keyauth.cc/t/process-error-bug/477/2</link>
        <pubDate>Fri, 22 Jul 2022 18:24:03 +0000</pubDate>
        <guid isPermaLink="false">community.keyauth.cc-post-477-2</guid>
        <source url="https://community.keyauth.cc/t/process-error-bug/477.rss">Process Error/Bug</source>
      </item>
      <item>
        <title>Process Error/Bug</title>
        <dc:creator><![CDATA[Blaze_Escape]]></dc:creator>
        <description><![CDATA[
            <p><img src="https://community.keyauth.win/uploads/default/original/1X/e9ee3d849c8fa2e33258c206ef84a04c029fecf6.png" alt="image" data-base62-sha1="xnrG2Fqw0csGXPQMnFt3BHAnAiy" width="612" height="38"></p>
          <p><a href="https://community.keyauth.cc/t/process-error-bug/477/1">Read full topic</a></p>
        ]]></description>
        <link>https://community.keyauth.cc/t/process-error-bug/477/1</link>
        <pubDate>Fri, 22 Jul 2022 18:22:59 +0000</pubDate>
        <guid isPermaLink="false">community.keyauth.cc-post-477-1</guid>
        <source url="https://community.keyauth.cc/t/process-error-bug/477.rss">Process Error/Bug</source>
      </item>
  </channel>
</rss>
